name: Composite java action
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Build step
        run: echo "Hello, ${{secreats.DOCKER_PASSWORD}}"
