name: github actions demo
on:
  push:
    branches: ["master"]
jobs:
  action-demo:
    runs-on: ubuntu-latest  
    steps:
      - name: checkout the code
        uses: actions/checkout@v6 
      - name: print index.html page
        run: cat index.html
