name: context workflow
on: push
jobs: 
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: use context variable
        run: |
          echo " this workflow is triggered by ${{ github.actor }} "
          echo " the repository name is ${{ github.repository }} "
          echo " the branch is ${{ github.ref_name }}"

      - name: use context variable
        run: |
          echo "${{ toJSON(github) }}"
          
